if(!require("colourpicker"))   install.packages("colourpicker")
if(!require("pivotea"))        install.packages("pivotea")
if(!require("openxlsx"))       install.packages("openxlsx")
if(!require("reactable"))      install.packages("reactable")
if(!require("fs"))             install.packages("fs")
if(!require("shiny"))          install.packages("shiny")

source("convex.R")
source("file.R")
source("highlight.R")
source("pivotea.R")
source("utils_border.R")
source("utils_window.R")
